### ISSUE TITLE
Consider permanently redirecting to new library home

### ISSUE THREAD

**Issue by kingsleyadio** [hellofresh/android-deeplink#75]
As this library is now deprecated, you may consider redirecting it to my [fork](https://github.com/kingsleyadio/android-deeplink), which will continue to be maintained indefinitely

I had originally tried reaching out to transfer the ownership directly, but couldn't get a hold of anyone. So I went ahead to fork it

Kindly let me know if this is possible, and whatever else I need to do to make it happen

Thank you.

**Comment by konstantin-kiriushyn** [comment]
Hi Kingsley! 

Thank you very much for taking care of it. I would be happy to add a redirect link to the README.

**Comment by konstantin-kiriushyn** [comment]
https://github.com/hellofresh/android-deeplink/pull/76
